config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'artist#index'
  resources :albums

  concern :api_default do
    resources :artist_list
  end

  # versionament of api
  namespace :api, constraints: { format: 'json' } do
    concerns :api_default
  end
end

app/models/album.rb
class Album < ApplicationRecord
      validates :name, presence: true, length: { minimum: 2 }
   
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  validates :username, presence: true,
                       uniqueness: { case_sensitive: false, message: 'must be given please' }
  enum roles: { admin: 'admin', user: 'user' }

  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_albums, only: %i[edit update destroy]

  include ArtistHelper
  def index
    @title = 'All Albums | LofiMusic'
    @albums = Album.all
  end

  def new
    @title = 'New Album | LofiMusic'
    response = api_artist(nil)
    @json = JSON.parse response
    @albums = Album.new
  end

  def create
    response = api_artist(nil)
    @json = JSON.parse response
    @albums = Album.new(albums_params)
    respond_to do |format|
      if @albums.save
        format.html { redirect_to albums_path, notice: 'A new album was successfully created' }
      else
        format.html { render :new, alert: @albums.errors.full_messages }
      end
    end
  end

  def edit
    @title = 'Edit Album | LofiMusic'
    response = api_artist(nil)
    @json = JSON.parse response
  end

  def update
    response = api_artist(nil)
    @json = JSON.parse response
    respond_to do |format|
      if @albums.update(albums_params)
        format.html { redirect_to albums_path, notice: "The album (<b>#{@albums.name}</b>) was successfully updated.".html_safe }

      else
        format.html { render :edit, status: :unprocessable_entity }

      end
    end
  end

  def destroy
    @albums.destroy
    respond_to do |format|
      format.html { redirect_to albums_path, notice: "The album (<b>#{@albums.name}</b>) was successfully updated.".html_safe }
    end
  end

  private

  def set_albums
    @albums = Album.find(params[:id])
  end

  def albums_params
    params.require(:album).permit(:name, :artist, :year)
  end
end

app/controllers/api/artist_list_controller.rb
module Api
  class ArtistListController < ApplicationController
    include ArtistHelper
    def index
      response = api_artist(nil)
      render json: response, status: :ok
    end

    def show
      response = api_artist(params[:id])
      render json: response, status: :ok
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :set_params_permitted, if: :devise_controller?

  protected

  def set_params_permitted
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[full_name username email role])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[full_name username email role])
  end
end

app/controllers/artist_controller.rb
class ArtistController < ApplicationController
  def index
  @title = "List All Artist || LofiMusic"
  end
end

app/helpers/album_helper.rb
module AlbumHelper
  def year_range
    Time.zone.now.year - 100..Time.zone.now.year 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def toastr_flash
    flash.each_with_object([]) do |(type, message), flash_messages|
      type = 'success' if type == 'notice'
      type = 'error' if type == 'alert'
      text = "<script>toastr.#{type}('#{message}', '', { closeButton: true, progressBar: true })</script>"
      flash_messages << text.html_safe if message
    end.join("\n").html_safe
  end
end

app/helpers/artist_helper.rb
module ArtistHelper
  def api_artist(_url_params)
    token = ENV['token']
    url = 'https://moat.ai/api/task'
    RestClient.get(url, basic: token, params: { artist_id: _url_params })
  end
end

app/helpers/heroicon_helper.rb
# frozen_string_literal: true

module HeroiconHelper
  include Heroicon::Engine.helpers
end

app/helpers/user_helper.rb
module UserHelper
  def is_user_logged(user)
    if user.role === 'user'
      "Welcome <b>#{user.full_name}</b>, you are logged as an user".html_safe
    else
      "Welcome <b>#{user.full_name}</b>, you are logged as an administrator".html_safe
    end
  end
end

app/views/albums/_form.html.erb
 
<% if album.errors.any? %>
  <div class="alert my-8 animate__animated animate__fade animate__delay-2s alert-error">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="w-6 h-6 mx-2 stroke-current">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18.364 18.364A9 9 0 005.636 5.636m12.728 12.728A9 9 0 015.636 5.636m12.728 12.728L5.636 5.636"></path>
    </svg>
   <%= pluralize(album.errors.count, "error") %> <br />
    <%= alert %>
    <hr>
    <% album.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <% end %>
  <% end %>
</div>

  <%= form_with(model: album) do |form| %>
    <div class="p-10 flex mx-auto w-4/6  card bg-base-200">
      <div class="form-control">
        <%= form.label :name, class:'label' %>
        <%= form.text_field :name, placeholder: 'Album name', class: 'input input-bordered'%>
      </div>
      <div class="form-control">
        <%= form.label :artist, class:'label' %>
        <%= form.select :artist, @json.collect{|artist| artist[0]['name']},
         class: 'select select-bordered w-full max-w-xs'%>
      </div>
      <div class="form-control">
        <%= form.label :year, class: 'label' %>
        <%=  form.select :year, year_range, class: 'input input-bordered'%>
      </div>
      <div class="form-control py-5">
        <%= button_tag(type: 'submit',  data: { disable_with: "Saving..." }, class: "btn btn-primary ") do %>
          <%= heroicon 'save' %> Save Album
        <% end %>
      </div>
    </div>
  <% end %>

app/views/albums/edit.html.erb
<% content_for :title do %>
  <%= @title %> | LofiMusic
<% end %>
<section class='container mx-auto h-screen max-w-5xl'>
  <div class="flex items-center justify-between py-4">
    <div>
      <h1 class='text-2xl'>Edit</h1>
    </div>
    <div>
    </div>
  </div>
  <%= render 'form', album: @albums %>
</section>

app/views/albums/index.html.erb
<% content_for :title do %>
  <%= @title %> | LofiMusic
<% end %>
<section class='container mx-auto h-screen max-w-5xl'>
  <div class="flex items-center justify-between py-4">
    <div>
      <h1 class='text-2xl'>All albums</h1>
    </div>
    <div>
      <% if current_user.role === 'user' %>
        <%= link_to new_album_path,  class: 'btn btn-primary' do %>
          <%= heroicon 'plus-circle' %>
          New Album
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="overflow-x-auto">
    <table class="table w-full">
      <thead>
        <tr>
          <th></th>
          <th>Album name</th>
          <th>Artist</th>
          <th>Year</th>
          <th class='flex justify-center'>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @albums.each do |album| %>
          <tr>
            <th><%= album.id %></th>
            <td><%= album.name %></td>
            <td><%= album.artist %></td>
            <td><%= album.year %></td>
            <td class="flex flex-row space-x-3 justify-center">
              <div>
                <% if current_user.role === 'user' %>
                  <%= link_to edit_album_path(album), class: 'btn btn-sm btn-info' do %>
                    <%= heroicon 'edit' %> Edit
                  <% end %>
                <% end %>
              </div>
              <div>
                <% if current_user.role === 'admin' %>
                  <%= link_to album_path(album), method: :delete, data: {confirm: "You are sure DELETE?"}, class: 'btn btn-sm btn-error delete' do %>
                    <%= heroicon 'trash' %> Remove
                  <% end %>
                <% end %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</section>

app/views/albums/new.html.erb
<% content_for :title do %>
  <%= @title %> | LofiMusic
<% end %>
<section class='container mx-auto h-screen max-w-5xl'>
  <div class="flex items-center justify-between py-4">
    <div>
      <h1 class='text-2xl'>New album</h1>
    </div>
    <div>
    </div>
  </div>
  <%= render 'form', album: @albums %>
</section>

app/views/artist/index.html.erb
<% content_for :title do %>
  <%= @title %> | LofiMusic
<% end %>
<section class='container mx-auto   max-w-5xl'>
  <div class="flex  justify-between py-4">
    <div>
      <h1 class='text-2xl'>All artists </h1>
    </div>
    <div>
    <% if current_user.role === 'user' %>
      <%= link_to new_album_path,  class: 'btn btn-primary' do %>
        <%= heroicon 'plus-circle' %> New Album
      <% end %>
      <% end %>
    </div>
  </div>
</div>
<div  id="app"></div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="light">
  <head>
    <title><%= content_for(:title) ? content_for(:title) : "LofiMusic" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag 'app_svelte' %>
    <%= stylesheet_pack_tag 'application' %>
  </head>
  <body>
    <%= render 'shared/header' %>
    <main class='container m-auto max-w-5xl'>
      <div class="mx-auto m-5">
        <%= render 'shared/mensagers' %>
      </div>
      <%= yield %>
    </main>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="text-gray-600 bg-gray-200 body-font">
  <div class="container max-w-5xl px-5 py-8 mx-auto flex items-center sm:flex-row flex-col">
    <a class="flex title-font font-medium items-center md:justify-start justify-center text-gray-900">
      <span class="ml-3 text-xl">LofiMusic</span>
    </a>
    <p class="text-sm text-gray-500 sm:ml-4 sm:pl-4 sm:border-l-2 sm:border-gray-200 sm:py-2 sm:mt-0 mt-4">
      © <%= Time.now.strftime('%Y') %> by Marvio Rocha
     
    </p>
   
      <a target="_blank" href="https://linkedin.com/in/marviorocha" class="ml-3 flex justify-end text-gray-500">
        <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="0" class="w-5 h-5" viewBox="0 0 24 24">
          <path stroke="none" d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z"></path>
          <circle cx="4" cy="4" r="2" stroke="none"></circle>
        </svg>
      </a>
    </span>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="text-gray border-b border-gray-300 body-font">
  <div class="container mx-auto flex flex-wrap  max-w-5xl p-5  flex-col md:flex-row justify-items-center">
    <a href='<%= root_url %>' class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
      <%= image_tag('Logo.svg', width: '235', height: '80') %>
    </a>
    <%= render 'shared/navigation' %>
  </div>
</header>

app/views/shared/_mensagers.html.erb
<% if alert %>
  <div class="alert animate__animated animate__bounce animate__delay-2s alert-error">
    <div class="flex-1">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="w-6 h-6 mx-2 stroke-current">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18.364 18.364A9 9 0 005.636 5.636m12.728 12.728A9 9 0 015.636 5.636m12.728 12.728L5.636 5.636"></path>
      </svg>
      <label><%= alert %></label>
    </div>
   
  </div>
<% end %>
<% if notice %>
  <div class="alert alert-info">
    <div class="flex-1">
      <%= heroicon 'check' %>
      <label><%= notice %></label>
    </div>
  </div>
<% end %>

app/views/shared/_navigation.html.erb
<nav class="md:ml-auto flex flex-wrap space-x-4  my-4 text-base justify-end">
  <% if(user_signed_in?) %>
    <div>
      <%= is_user_logged(current_user) %>
    </div>
    <div>
      <%= link_to 'Artists', root_path, class: 'link mr-5 font-bold hover:text-gray-900' %>
      <%= link_to 'Albums', albums_path, class: 'link mr-5 font-bold hover:text-gray-900' %>
    </div>
    <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-sm btn-primary' %>
  <% else %>
    <a href='<%= new_user_registration_path %>' class="btn btn-sm btn-info">Sign up</a>
    <a href='<%= new_user_session_path %>' class="btn btn-sm btn-primary">Login</a>
  <% end %>
</nav>